seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-blood-transfusion-service-center-tid=10101-fold=1"

[optimizer]
type = "AdamW"
lr = 0.0006079203898818125
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 1
d_layer = 947
dropout = 0.07472415232899687
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 86
frequency_scale = 0.04466545255928128
d_embedding = 46
lite = true
