seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361241-ctr23_361241-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.39650574084698464
depth = 13
l2_leaf_reg = 5.854601439095001
leaf_estimation_iterations = 9
learning_rate = 0.11956244022128884
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
