seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361250-ctr23_361250-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.6180154289988415
depth = 8
l2_leaf_reg = 1.4411932358022574
leaf_estimation_iterations = 3
learning_rate = 0.051273708746284376
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
