seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-balance-scale-tid=11-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.7038885835403663
depth = 4
l2_leaf_reg = 9.202877876072268
leaf_estimation_iterations = 8
learning_rate = 0.9920670368929653
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
