seed = 0
n_trials = 30
timeout = "__null__"
function = "bin.tabr_scaling.main"

[sampler]

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[space.data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/CTR23-OpenML-tid=361244-ctr23_361244-seed=0"
y_policy = "standard"

[space.optimizer]
type = "AdamW"
lr = [ "_tune_", "loguniform", 1e-5, 0.001,]
weight_decay = [ "_tune_", "?loguniform", 0.0, 1e-6, 0.0001,]

[space.model]
num_embeddings = "__null__"
d_main = [ "_tune_", "int", 96, 384,]
context_dropout = [ "_tune_", "uniform", 0.0, 0.6,]
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = [ "_tune_", "uniform", 0.0, 0.6,]
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
