seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "__null__"
cache = true
cat_policy = "one-hot"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-tic-tac-toe-49"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.7073309699952618
gamma = 0.19087614756145965
lambda = 0.0
learning_rate = 0.07126995609048578
max_depth = 10
min_child_weight = 0.5030416925289531
subsample = 0.9718740392573121

[fit]
verbose = true
