seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "one-hot"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361268-ctr23_361268-fold=0-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.5915956810035584
lambda_l2 = 0.0
learning_rate = 0.3067750867937877
num_leaves = 7
min_sum_hessian_in_leaf = 1.1665388871103268
bagging_fraction = 0.6350039865960824

[fit]
