seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361243-ctr23_361243-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.6778165367962301
depth = 6
l2_leaf_reg = 7.378420819013689
leaf_estimation_iterations = 10
learning_rate = 0.005575186893674789
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
