seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-steel-plates-fault-tid=146817-fold=1"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.964648098788107
gamma = 0.004560256930305123
lambda = 0.0
learning_rate = 0.00354465593185329
max_depth = 10
min_child_weight = 0.00013202168674787394
subsample = 0.9144700146086815

[fit]
verbose = true
