seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "__null__"
cache = true
cat_policy = "one-hot"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-kr-vs-kp-3"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.7172083127790604
gamma = 0.07740325005042992
lambda = 0.0
learning_rate = 0.001591288390738432
max_depth = 11
min_child_weight = 0.05274497214807883
subsample = 0.7682896055543611

[fit]
verbose = true
