seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-diabetes-tid=37-fold=1"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.0008972612866432509
weight_decay = 1.62065673920372e-05

[model]
num_embeddings = "__null__"
d_main = 309
context_dropout = 0.023512675352592403
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.16968417754584575
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
