seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-first-order-theorem-proving-tid=9985-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.7252542798196405
depth = 9
l2_leaf_reg = 9.565227983759916
leaf_estimation_iterations = 7
learning_rate = 0.018688099841937894
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
