seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-madelon-tid=9976-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.6176354970758771
depth = 10
l2_leaf_reg = 6.207646569060094
leaf_estimation_iterations = 10
learning_rate = 0.11103525577197582
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
