seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-optdigits-tid=28-fold=0"

[optimizer]
type = "AdamW"
lr = 0.0005301307973946533
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 6
d_layer = 807
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 48
frequency_scale = 0.08490564561872228
d_embedding = 22
lite = true
