seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-analcatdata_authorship-tid=3549-fold=1"

[optimizer]
type = "AdamW"
lr = 0.00010061176409589714
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 3
d_layer = 646
dropout = 0.3300867687463425
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 39
frequency_scale = 2.9652527407725664
d_embedding = 37
lite = true
