seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361250-ctr23_361250-seed=0"

[optimizer]
type = "AdamW"
lr = 0.0009197266687466414
weight_decay = 1.9008376820188854e-05

[model.backbone]
type = "MLP"
n_blocks = 3
d_layer = 195
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 57
frequency_scale = 0.07893472784033653
d_embedding = 20
lite = true
