seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-ilpd-tid=9971-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.18319136200711683
depth = 10
l2_leaf_reg = 0.29906470725618617
leaf_estimation_iterations = 9
learning_rate = 0.0010329669551879738
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
