seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "one-hot"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361269-ctr23_361269-fold=1-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.5858148386307203
lambda_l2 = 0.0
learning_rate = 0.003980976140397894
num_leaves = 18
min_sum_hessian_in_leaf = 5.783439810485646
bagging_fraction = 0.61196234403019

[fit]
