seed = 0
n_trials = 30
timeout = "__null__"
function = "bin.ffn.main"

[sampler]

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[space.data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-mfeat-pixel-tid=146824-fold=1"

[space.optimizer]
type = "AdamW"
lr = [ "_tune_", "loguniform", 1e-5, 0.001,]
weight_decay = [ "_tune_", "?loguniform", 0.0, 1e-6, 0.0001,]

[space.model.backbone]
type = "MLP"
n_blocks = [ "_tune_", "int", 1, 6,]
d_layer = [ "_tune_", "int", 64, 1024,]
dropout = [ "_tune_", "?uniform", 0.0, 0.0, 0.5,]
activation = "ReLU"

[space.model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = [ "_tune_", "int", 16, 96,]
frequency_scale = [ "_tune_", "loguniform", 0.01, 100.0,]
d_embedding = [ "_tune_", "int", 16, 64,]
lite = true
