seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "one-hot"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-credit-approval-tid=29-fold=1"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.7143843504728831
gamma = 0.7076598458663511
lambda = 0.0
learning_rate = 0.09111763933595836
max_depth = 10
min_child_weight = 0.038771322271909624
subsample = 0.9482732979255315

[fit]
verbose = true
