seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361266-ctr23_361266-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.6399210213275238
depth = 4
l2_leaf_reg = 9.452222278790881
leaf_estimation_iterations = 6
learning_rate = 0.017538232373118037
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
