seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361235-ctr23_361235-fold=1-seed=0"

[optimizer]
type = "AdamW"
lr = 0.0007634057195296406
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 6
d_layer = 345
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 17
frequency_scale = 0.2448691488904506
d_embedding = 23
lite = true
