seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-diabetes-tid=37-fold=1"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.6991105311080459
gamma = 0
lambda = 0.0
learning_rate = 0.029605774428600143
max_depth = 5
min_child_weight = 0.0033584500281308334
subsample = 0.5290145801619378

[fit]
verbose = true
