seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-isolet-tid=3481-fold=0"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.0007717846862118063
weight_decay = 0.0

[model]
num_embeddings = "__null__"
d_main = 222
context_dropout = 0.4185787175563589
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.0361352829775619
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
