seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-eucalyptus-tid=2079-fold=1"

[optimizer]
type = "AdamW"
lr = 0.00011834731850968474
weight_decay = 2.715150883792444e-06

[model.backbone]
type = "MLP"
n_blocks = 4
d_layer = 317
dropout = 0.16000857541123392
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 47
frequency_scale = 2.2556330753420246
d_embedding = 56
lite = true
