seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-kc2-tid=3913-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.896546595851063
depth = 7
l2_leaf_reg = 4.415062760129706
leaf_estimation_iterations = 9
learning_rate = 0.26216938007596374
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
