seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361621-ctr23_361621-fold=1-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.8315391015500504
lambda_l2 = 0.0
learning_rate = 0.18842388825327847
num_leaves = 248
min_sum_hessian_in_leaf = 0.019988645463995935
bagging_fraction = 0.7941585567768028

[fit]
