seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/CTR23-OpenML-tid=361268-ctr23_361268-fold=1-seed=0"
y_policy = "standard"

[optimizer]
type = "AdamW"
lr = 0.0008401891913442231
weight_decay = 1.5278610607077096e-05

[model]
num_embeddings = "__null__"
d_main = 261
context_dropout = 0.13384897958437098
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.571649406910191
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
