seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361244-ctr23_361244-fold=1-seed=0"

[optimizer]
type = "AdamW"
lr = 0.00018111886467330683
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 5
d_layer = 242
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 33
frequency_scale = 61.586051660398354
d_embedding = 51
lite = true
