seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "one-hot"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-cylinder-bands-14954"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.7744067519636624
gamma = 0
lambda = 0.0
learning_rate = 0.08663279761354557
max_depth = 8
min_child_weight = 22.420123713724433
subsample = 0.9818313802505146

[fit]
verbose = true
