seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361241-ctr23_361241-fold=1-seed=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.5271689941696268
gamma = 0
lambda = 0.0
learning_rate = 0.010865633249460467
max_depth = 14
min_child_weight = 1.6845597184634453
subsample = 0.515919464765654

[fit]
verbose = true
