seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-CIFAR_10-tid=167124-fold=0"

[model]
n_estimators = 10
n_jobs = -1
early_stopping_rounds = 200
feature_fraction = 0.5355180290989434
lambda_l2 = 0.0
learning_rate = 0.31467304061660045
num_leaves = 599
min_sum_hessian_in_leaf = 16.59865466307128
bagging_fraction = 0.989309171116382

[fit]
