seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-Fashion-MNIST-tid=146825-fold=0"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 8.17147891511587e-05
weight_decay = 0.0

[model]
num_embeddings = "__null__"
d_main = 274
context_dropout = 0.3672574336334528
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.37016039812485413
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
