seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361255-ctr23_361255-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.359507900573786
depth = 8
l2_leaf_reg = 7.006548839679922
leaf_estimation_iterations = 1
learning_rate = 0.10006913513545575
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
