seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-kc2-tid=3913-fold=1"

[optimizer]
type = "AdamW"
lr = 0.00038322168504927853
weight_decay = 7.098936257405907e-05

[model.backbone]
type = "MLP"
n_blocks = 1
d_layer = 147
dropout = 0.38907837547492524
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 86
frequency_scale = 82.12461922256875
d_embedding = 55
lite = true
