seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-pc3-tid=3903-fold=0"

[optimizer]
type = "AdamW"
lr = 0.0006418587699324591
weight_decay = 1.475543909738732e-05

[model.backbone]
type = "MLP"
n_blocks = 6
d_layer = 344
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 17
frequency_scale = 52.25372642279878
d_embedding = 48
lite = true
