seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-bank-marketing-14965"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
d_main = 220
context_dropout = 0.5379279575106378
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.2205371220287379
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 7.442688632875928e-05
weight_decay = 0.0
