seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-Bioresponse-tid=9910-fold=0"

[model]
iterations = 100
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.2653894909394454
depth = 9
l2_leaf_reg = 1.0300110565085727
leaf_estimation_iterations = 6
learning_rate = 0.6136045802294308
task_type = "CPU"
thread_count = -1

[fit]
logging_level = "Verbose"
