seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "__null__"
cache = true
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-dna-tid=167140-fold=1"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.6870849901671128
gamma = 0
lambda = 0.17181604264581885
learning_rate = 0.03565638590821156
max_depth = 4
min_child_weight = 2.0005899701171863
subsample = 0.6980298514036469

[fit]
verbose = true
