seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "one-hot"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361272-ctr23_361272-fold=1-seed=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.8409101495517417
gamma = 3.0772018129755754
lambda = 2.194197617900576
learning_rate = 0.004277083049962069
max_depth = 4
min_child_weight = 0.007808544786049685
subsample = 0.6818553854713113

[fit]
verbose = true
