seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361623-ctr23_361623-fold=1-seed=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.7941585567768028
gamma = 0
lambda = 0.0
learning_rate = 0.2478223675958974
max_depth = 5
min_child_weight = 52.08947038818605
subsample = 0.8437441381939077

[fit]
verbose = true
