seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-madelon-tid=9976-fold=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.8626271399098202
gamma = 1.6593996576192835
lambda = 0.10924118351371671
learning_rate = 0.008030164648270104
max_depth = 10
min_child_weight = 0.0055013039835233235
subsample = 0.8090077144994208

[fit]
verbose = true
