seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-pendigits-tid=32-fold=1"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.0007220917699605242
weight_decay = 1.8348295456200723e-06

[model]
num_embeddings = "__null__"
d_main = 303
context_dropout = 0.17364365576832066
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.1099148172042701
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
