seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361249-ctr23_361249-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.31856895245132366
depth = 11
l2_leaf_reg = 1.4047988378034826
leaf_estimation_iterations = 8
learning_rate = 0.007382751981499335
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
