seed = 0
n_trials = 30
timeout = "__null__"
function = "bin.catboost_.main"

[sampler]

[space]
seed = 0

[space.data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361251-ctr23_361251-seed=0"

[space.model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = [ "_tune_", "uniform", 0.0, 1.0,]
depth = [ "_tune_", "int", 3, 14,]
l2_leaf_reg = [ "_tune_", "uniform", 0.1, 10.0,]
leaf_estimation_iterations = [ "_tune_", "int", 1, 10,]
learning_rate = [ "_tune_", "loguniform", 0.001, 1.0,]
task_type = "CPU"
thread_count = 4

[space.fit]
logging_level = "Verbose"
