seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-texture-tid=125922-fold=1"

[optimizer]
type = "AdamW"
lr = 0.0004548624208721939
weight_decay = 3.4674958213764543e-06

[model.backbone]
type = "MLP"
n_blocks = 5
d_layer = 988
dropout = 0.2960209656359195
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 62
frequency_scale = 0.07804166575000096
d_embedding = 62
lite = true
