seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "one-hot"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361236-ctr23_361236-fold=0-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.8675970110612974
lambda_l2 = 0.0
learning_rate = 0.053514565455295114
num_leaves = 456
min_sum_hessian_in_leaf = 0.2713385093212272
bagging_fraction = 0.6115408163203091

[fit]
