seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361257-ctr23_361257-fold=1-seed=0"

[optimizer]
type = "AdamW"
lr = 0.0005147622432383661
weight_decay = 2.883906161101796e-05

[model.backbone]
type = "MLP"
n_blocks = 2
d_layer = 564
dropout = 0.009260897230306986
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 80
frequency_scale = 0.07865000457856676
d_embedding = 32
lite = true
