seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-pc1-tid=3918-fold=1"

[optimizer]
type = "AdamW"
lr = 0.0007180630624021837
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 1
d_layer = 661
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 91
frequency_scale = 2.8566946659136536
d_embedding = 42
lite = true
