seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-cnae-9-tid=9981-fold=1"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.000906226347126195
weight_decay = 0.0

[model]
num_embeddings = "__null__"
d_main = 321
context_dropout = 0.07096465552135993
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.38395261279651427
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
