seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "one-hot"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-churn-tid=167141-fold=1"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.6077538385567792
gamma = 0
lambda = 0.0
learning_rate = 0.03585932759723227
max_depth = 3
min_child_weight = 0.001757196998010447
subsample = 0.7123427343757531

[fit]
verbose = true
