seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361617-ctr23_361617-fold=0-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.6991105311080459
lambda_l2 = 0.0
learning_rate = 0.6809530508136838
num_leaves = 569
min_sum_hessian_in_leaf = 0.08765018795171545
bagging_fraction = 0.6137073139866616

[fit]
