seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361269-ctr23_361269-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.16130951788499626
depth = 10
l2_leaf_reg = 2.607586865143843
leaf_estimation_iterations = 5
learning_rate = 0.005410990556767876
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
