seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361616-ctr23_361616-seed=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.6706378696181594
depth = 5
l2_leaf_reg = 1.376370346783048
leaf_estimation_iterations = 4
learning_rate = 0.012334805700860018
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
