seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-climate-model-simulation-crashes-146819"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
d_main = 116
context_dropout = 0.05227757982092442
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.01213103846419543
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.0004626362841475585
weight_decay = 9.062263471261964e-05
