seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361241-ctr23_361241-fold=1-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.7119275242790899
lambda_l2 = 0.0
learning_rate = 0.008030164648270104
num_leaves = 509
min_sum_hessian_in_leaf = 0.0055013039835233235
bagging_fraction = 0.8090077144994208

[fit]
