seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "one-hot"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361267-ctr23_361267-seed=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.5740704304740825
gamma = 0
lambda = 0.5459705437699814
learning_rate = 0.0025745469436710515
max_depth = 12
min_child_weight = 0.0013774868811120627
subsample = 0.755659491273228

[fit]
verbose = true
