seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "one-hot"
y_policy = "standard"
cache = true
path = ":data/CTR23-OpenML-tid=361252-ctr23_361252-fold=0-seed=0"

[model]
n_estimators = 4000
n_jobs = 4
early_stopping_rounds = 200
feature_fraction = 0.7906364363179293
lambda_l2 = 0.0
learning_rate = 0.1498866107685077
num_leaves = 387
min_sum_hessian_in_leaf = 54.51321655355952
bagging_fraction = 0.8219950996148186

[fit]
