seed = 0

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"
cache = true
path = ":data/TabZilla-OpenML-adult-tid=7592-fold=0"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.317983179393976
depth = 7
l2_leaf_reg = 0.7350602138529652
leaf_estimation_iterations = 7
learning_rate = 0.05009615137983937
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
