seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/TabZilla-OpenML-dresses-sales-tid=125920-fold=0"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.00019407982792082253
weight_decay = 1.0924118351371678e-06

[model]
num_embeddings = "__null__"
d_main = 183
context_dropout = 0.396104122495611
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.17404656432626645
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
