seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-GesturePhaseSegmentationProcessed-14969"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.9706888523532493
gamma = 0
lambda = 0.0
learning_rate = 0.3522335062770539
max_depth = 10
min_child_weight = 0.0001200663052709496
subsample = 0.6736167589661097

[fit]
verbose = true
