seed = 0
neighbors = "__null__"

[data]
seed = 0
num_policy = "quantile"
cache = true
cat_policy = "__null__"
y_policy = "standard"
path = ":data/CTR23-OpenML-tid=361237-ctr23_361237-fold=1-seed=0"

[model]
booster = "gbtree"
early_stopping_rounds = 200
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_byree = 0.8925764560115689
gamma = 0.0020882203831644325
lambda = 5.6625296703939565
learning_rate = 0.010338960009667775
max_depth = 14
min_child_weight = 0.0024558947958866163
subsample = 0.9746594112078407

[fit]
verbose = true
