seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
num_policy = "__null__"
cat_policy = "ordinal"
y_policy = "__null__"
path = ":data/TabZilla-OpenML-kr-vs-kp-tid=3-fold=0"

[optimizer]
type = "AdamW"
lr = 1.8661567862395527e-05
weight_decay = 1.519656816607237e-05

[model.backbone]
type = "MLP"
n_blocks = 4
d_layer = 691
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 88
frequency_scale = 0.2952891435379983
d_embedding = 37
lite = true
