seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
num_policy = "quantile"
cat_policy = "__null__"
path = ":data/CTR23-OpenML-tid=361257-ctr23_361257-seed=0"
y_policy = "standard"

[optimizer]
type = "AdamW"
lr = 7.50195444362012e-05
weight_decay = 5.846326121643419e-06

[model]
num_embeddings = "__null__"
d_main = 324
context_dropout = 0.31733695185174265
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.3408267366563594
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"
